export enum ROOT_ROUTES {
  HOME = 'HOME',
  MORE_INFORMATION = 'MORE_INFORMATION',
  ITEM_CHOICE = 'ITEM_CHOICE',
  RIGHT_DRAWER = 'RIGHT_DRAWER',
  LEFT_DRAWER = 'LEFT_DRAWER',
  CARTOON_SCREEN = 'CARTOON_SCREEN',
}

export enum HOME_ROUTES {
  RIGHT_DRAWER = 'RIGHT_DRAWER',
  LEFT_DRAWER = 'LEFT_DRAWER',
}
